gui:
  border: rounded
  nerdFontsVersion: "3"
  showIcons: true
  showFileIcons: true
  showCommandLog: true
  showRandomTip: false
  splitDiff: auto
  theme:
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#6c7086"
    searchingActiveBorderColor:
      - "#94e2d5"
      - bold
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    inactiveViewSelectedLineBgColor:
      - "#181825"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    cherryPickedCommitBgColor:
      - "#94e2d5"
    markedBaseCommitFgColor:
      - "#1e1e2e"
    markedBaseCommitBgColor:
      - "#f9e2af"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"

git:
  autoFetch: true
  autoRefresh: true
  fetchAll: true
